#Contributor: Riley Berman 
#Description: Preforms analysis of data generated by RileyBerman_LegiScan_Combine.R. 
#Methodology: Tidyverse manipulating and graphing with ggplot2. 

rm(list = ls())

library(tidyverse)
library(janitor)
library(ggplot2)
library(hrbrthemes)
library(tidylog)

# ---- Opening bill data ----

#These are all the bills that have been recorded (44,066)
#(counting the unique number of bills in the history, documents tibbles give a roughly similar row number)  
bills <- read_csv("LegiScan_CA_Combined/bills_combined.csv") 

#Source: (https://www.assembly.ca.gov/public-services/glossary)
#There are different types of bills identified by there letters in bill_number:
#AB: Assembly Bill
#ACR: Assembly Concurrent Resolution
#AR: Assembly Rules
#SB: Senate Bill
#SCR: Senate Concurrent Resolution
#SB: Senate Rules
#SJR: Senate Joint Resolution
#ACA: Assembly Constitutional Amendment 
#AJR: Assembly Joint Resolution
#SCA: Senate Concurrent Amendment
#HB: House Bill
#HR: House Resolution

#Source: (https://en.wikipedia.org/wiki/California_State_Legislature)
#The addition of "X" to the bill_number indicates that the bill in question occurred in a special session (extraordinary session)

#Separating bill_number into two pieces
bills_updated <- bills |>
  extract(bill_number, into = c("bill_letter", "bill_numbers"), regex = "([A-Z]+)(\\d+)", remove = FALSE) |>
  mutate(year = year(status_date)) |>
  #Let's drop the 2025 bills, since they are not fully recorded yet
  filter(year < 2025)

#Frequency of Bills by Type
#Note: Majority are Assembly Bills (AB) and Senate Bills (SB) ~ 90%!
SB_AB_proportion <- bills_updated |> 
  mutate(SB_or_AB = ifelse(str_detect(bill_letter, "AB|SB"), 1, 0)) |>
  summarize(SB_AB_proportion = mean(SB_or_AB, na.rm = TRUE)) |>
  pull(SB_AB_proportion)
  
#Note: Very few bills occur under special/extraordinary sessions ("X")
bill_type_frequency <- bills_updated |> 
  ggplot(aes(x = bill_letter)) + 
  geom_bar() +
  labs(title = "Frequency of Bills by Type", 
       x = "Bill Type", 
       y = "Frequency") +
  theme_minimal()

#By year
#Note: Looks like AB and SB bills are the most common, with AB bills being more common than SB bills
bill_type_frequency_year <- bills_updated |> 
  ggplot(aes(x = bill_letter)) + 
  geom_bar() +
  facet_wrap(~year) +
  labs(title = "Frequency of Bills by Type by Year", 
       x = "Bill Type", 
       y = "Frequency") +
  theme_minimal() + 
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

#What about special session bill frequency? 
#Note: Lot of special session bills in 2009, some in 2010, 2016
special_session_frequency <- bills_updated |> 
  filter(str_detect(bill_letter, "X")) |> 
  ggplot(aes(x = year)) + 
  geom_bar() + 
  labs(title = "Frequency of Special Session Bills by Year", 
       x = "Year", 
       y = "Frequency") +
  theme_minimal() + 
  scale_x_continuous(breaks = seq(min(bills_updated$year), max(bills_updated$year), by = 2))

#Separate "X" from the bill_number and filter for just SB and AB bills
bills_SB_AB <- bills_updated |>
  filter(str_detect(bill_letter, "AB|SB")) |>
  extract(bill_letter, into = c("bill_letter", "special_session"), regex = "^([A-Z]+?)(X)?$") 

#Source: https://calmatters.org/politics/2024/12/california-assembly-bill-limit/
#Limitations on introducing bills from 50 to 35 in the Assembly and from 40 to 35 in the senate in the two-year legislative period.

#What about the frequency of AB + SB bills?
#Note: 2014 has a very low amount of AB + SB bills
#Note: SB and AB bill frequency move with each other 
#Note: Up-and-down yearly cyclical pattern from 2015 to 2024
#Note: Makes sense for biennial California legislature--lawmakers introduce bills in first odd-numbered years, 
#then work on them in even-numbered years (they also campaign in even-numbered years)
SB_AB_bill_frequency <- bills_SB_AB |> 
  summarize(count = n(), 
            .by = c(bill_letter, year)) |>
  ggplot(aes(x = year, y = count, color = bill_letter)) + 
  geom_line() + 
  geom_point(alpha = 0.9) + 
  labs(title = "Frequency of AB and SB Bills by Year", 
       x = "Year", 
       y = "Frequency") +
  theme_minimal() + 
  scale_x_continuous(breaks = seq(min(bills_SB_AB$year), max(bills_SB_AB$year), by = 2))

#Note: from now on, we will only be looking at AB and SB bills

#Because bills are 2-year cyclical, I think it makes sense to analyze bills grouped by their 2-year periods
#Example: year = 2015, so part of 2015-2016 session
bills_SB_AB <- bills_SB_AB |> mutate(session_year = ifelse(year %% 2 == 0, paste0(year - 1, "-", year), paste0(year, "-", year + 1)))

#How often do bills pass/fail? 
#Note: Bit tricky, since some bills die out and are not recorded as "failed" or "passed"--for now, we table this
#Note: For example, look at any "Introduced" bill from 2009 
#Note: Looks like slight decline in failed bills (at the very least, this is an underestimate)
bill_status_distribution <- bills_SB_AB |>
  summarize(count = n(), 
            .by = c(status_desc, session_year)) |>
  mutate(status_proportion = count/sum(count, na.rm = TRUE), .by = session_year) |>
  ggplot(aes(x = session_year, y = status_proportion, color = status_desc, group = status_desc)) +
  geom_line() + 
  labs(title = "Distribution of Bill Status by Session Year", 
       x = "Session Year", 
       y = "Proportion of Bills") + 
  theme_minimal() + 
  scale_color_brewer(palette = "Set1") 

#Let's just look at the bills that are either "Passed," or "Failed"
#Many bills that aren't explicitly labeled as failed will have "failed passage" or "died" in last_action column 
#Let's count those as failed as well--creating a new column
bills_SB_AB <- bills_SB_AB |>
  mutate(real_status_desc = ifelse(str_detect(last_action, regex("\\b(failed|died)\\b", ignore_case = TRUE)), 
                              "Failed", status_desc))
#Graphing
#Note: Failed bill proportion spiking in 2015-2016 session                     
bill_pass_fail <- bills_SB_AB |>
  summarize(count = n(), 
           .by = c(real_status_desc, session_year)) |>
  mutate(status_proportion = count/sum(count, na.rm = TRUE), .by = session_year) |>
  ggplot(aes(x = session_year, y = status_proportion, color = real_status_desc, group = real_status_desc)) +
  geom_line() + 
  labs(title = "Distribution of Modified Bill Status by Session Year", 
       x = "Session Year", 
       y = "Proportion of Bills") + 
  theme_minimal() + 
  scale_color_brewer(palette = "Set1") 

#Does this change for AB and SB bills?
#Note: Fairly consistent trends across AB and SB bills
bills_SB_AB_pass_fail <- bills_SB_AB |>
  summarize(count = n(), 
            .by = c(real_status_desc, session_year, bill_letter)) |>
  mutate(status_proportion = count/sum(count, na.rm = TRUE), .by = c(session_year, bill_letter)) |>
  ggplot(aes(x = session_year, y = status_proportion, color = real_status_desc, group = real_status_desc)) +
  geom_line() + 
  labs(title = "Distribution of Adjusted Bill Status by Year", 
       x = "Session Year", 
       y = "Proportion of Bills") + 
  theme_minimal() + 
  scale_color_brewer(palette = "Set1") + 
  facet_wrap(~bill_letter)

#Source: https://www.dgs.ca.gov/Resources/SAM/TOC/6000/6905
#Regular sessions begin on the first Monday in December in each even-number year (i.e., following the election the preceding November)
#and end November 30 two years from then. 
#Example: 2017-2018 session begins in December 2016 and ends in November 2018 ~ roughly two years

# ---- Opening people data ----

#Let's weight by seat share of Democrats and Republicans
people <- read_csv("LegiScan_CA_Combined/people_combined.csv") |>
  extract(folder, into = c("session_year"), regex = "^(.+?)_Regular_Session") |>
  #people_id also includes entities like "Elections and Constitutional Amendments" and "Transportation," however these have no first_name value
  filter(!is.na(first_name))

#Any independents? 
#Note: One man, Chad Mayes
independents <- people |> filter(str_detect(party, "I")) |> pull(name)

#Exclude this 1 independent
people_updated <- people |> filter(!str_detect(party, "I")) 

#How does proportion of Democrats and Republicans change over time? 
#Note: Should roughly correspond to these numbers (https://ballotpedia.org/California_State_Legislature)
#Note: Both chambers of the California legislature have been controlled by the Democratic Party since 1959 
#except from 1969 to 1971 when the Republican Party held both chambers and from 1994 to 1996, when Republicans 
#briefly held a majority in the Assembly.
#Note: There are sometimes more or less than 120 total members (special appointments, deaths, vacancies, etc.)
#For example, Ted Gaines and Brian Dahle both represented SD-001 in the 2019-2020 special session year. 
#Looking into it, it looks like Ted Gaines actually left early--tenure was January 6, 2011–January 7, 2019--because he resigned his 
#position and picked up a new office as a Member of the California State Board of Equalization 
#(Source: https://en.wikipedia.org/wiki/Ted_Gaines, https://www.placer.ca.gov/DocumentCenter/View/34582/19A-PDF)
#Since people_id seems to be chronological (i.e., people with smaller people_id's were in office earlier), 
#we will just select for the most recent people_id if there are multiple politicians for the same district
people_updated <- people_updated |> 
  filter(people_id == max(people_id, na.rm = TRUE), 
         .by = c(session_year, role, district)) 

#Another problem: it is also the case that sometimes a politician who has ended their tenure is listed in the next session year
#Example: Susan Eggman ended her tenure in the Assembly by taking over for Cathleen Galgiani in 2020, 
#so I don't know why Susan is listed here (it should be for the 2021-2022 session_year)
#Both represent district "SD-005"
DR_proportion <- people |>
  summarize(total_republicans = sum(party == "R", na.rm = TRUE), 
            total_democrats = sum(party == "D", na.rm = TRUE), 
            total_members = total_republicans + total_democrats, 
            republican_percentage = total_republicans/total_members,
            democrat_percentage = total_democrats/total_members,
            .by = c(session_year, role))

#Because of this, I will locate and source this information from an outside source
source("RileyBerman_PartyProportions.R", local = TRUE)

#Graphing
#Note: Democrat proportion has been higher than Republican proportion and increasing in recent years
#Similar trends in both Assembly and Senate
#Note: Since 1993-1994 session, there have been no independents in Senate and a total of two independents in Assembly
#Note: For this reason, I will not include Independents in the graph
DR_proportion_plot <- senate_assembly_count_table |>
  ggplot(aes(x = session_year)) + 
  geom_line(aes(y = democrat_percentage, color = "Democrat Percentage"), group = 1) + 
  geom_point(aes(y = democrat_percentage, color = "Democrat Percentage")) +
  geom_line(aes(y = republican_percentage, color = "Republican Percentage"), group = 1) +
  geom_point(aes(y = republican_percentage, color = "Republican Percentage")) +
  labs(title = "Proportion of Democrats and Republicans by Session Year", 
       x = "Session Year", 
       y = "Proportion") +
  scale_color_manual(values = c("Democrat Percentage" = "blue", "Republican Percentage" = "red")) +
  theme_ipsum() + 
  theme(legend.position = "bottom") + 
  facet_wrap(~role) + 
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

# ---- Back to bill data (bipartisanship) ----

#How are bipartisan bills doing?
#There are many ways to define and score bipartisan bills--and more complicated ones (ex: https://www.thelugarcenter.org/ourwork-43.html)
#Through sponsorship... 
#Method 1: Say a bill is bipartisan1 if it at least one member of both parties are sponsors
##Method 2: Say a bill is bipartisan2 if it at least 25% of its sponsors are members of the opposing party
#Method 3: Define a bipartisan score as: minority_sponsors/majority_sponsors (bounded from 0 to 1)
#Consider maybe using Shannon Diversity Index, but there are really only 2 types of party sponsorship
#(Source: https://en.wikipedia.org/wiki/Diversity_index)
#Note: There are 3 types of sponsors: D (Democrat), R (Republican), I (Independent)
#Note: Only 63 bills out of 38,860 have an independent sponsor (Chad Mayes, 2021-2022 Regular Session) -- let's just exclude them 
#bills_SB_AB |> filter(str_detect(party_sponsors, "I")) |> nrow()
bills_SB_AB_updated <- bills_SB_AB |> filter(!str_detect(party_sponsors, "I"))

#To access weighted measures, merge bills_SB_AB_updated with senate_assembly_year (has no role column and independents)
bills_SB_AB_weighted <- bills_SB_AB_updated |>
  left_join(senate_assembly_year |> select(republican_percentage, democrat_percentage, session_year), by = c("session_year"))

#Constructing bipartisan metrics (absolute and weighted)
#Note: technically, we are using an aggregate of both Senate and Assembly proportions, however we have seen that these are fairly similar
bills_SB_AB_bipartisanship <- bills_SB_AB_weighted |>
  mutate(democrat_sponsors = str_count(party_sponsors, "D"),
         republican_sponsors = str_count(party_sponsors, "R"),
         minority_sponsors = pmin(democrat_sponsors, republican_sponsors, na.rm = TRUE), 
         majority_sponsors = pmax(democrat_sponsors, republican_sponsors, na.rm = TRUE), 
         total_sponsors = democrat_sponsors + republican_sponsors, 
         bipartisan1 = ifelse(democrat_sponsors > 0 & republican_sponsors > 0, 1, 0), 
         #Note: 0/0 = NA
         bipartisan2 = ifelse(minority_sponsors/total_sponsors >= 0.25, 1, 0), 
         bipartisan3 = minority_sponsors/majority_sponsors,
         weighted_republican_sponsors = republican_sponsors/republican_percentage,
         weighted_democrat_sponsors = democrat_sponsors/democrat_percentage,
         weighted_minority_sponsors = pmin(weighted_democrat_sponsors, weighted_republican_sponsors, na.rm = TRUE), 
         weighted_majority_sponsors = pmax(weighted_democrat_sponsors, weighted_republican_sponsors, na.rm = TRUE), 
         weighted_total_sponsors = weighted_democrat_sponsors + weighted_republican_sponsors, 
         weighted_bipartisan2 = ifelse(weighted_minority_sponsors/weighted_total_sponsors >= 0.25, 1, 0),
         weighted_bipartisan3 = weighted_minority_sponsors/weighted_majority_sponsors)

#How has bipartisanship (1, 2) changed over time?
#Graphing (absolute count)
#Note: Spikes in 2009-2010 and 2015-2016 sessions
#Note: bipartisan2 is a subset of bipartisan1, so it should be less than or equal to bipartisan1
bipartisan_count <- bills_SB_AB_bipartisanship |>
  summarize(total_bipartisan1 = sum(bipartisan1, na.rm = TRUE), 
            total_bipartisan2 = sum(bipartisan2, na.rm = TRUE), 
            weighted_total_bipartisan2 = sum(weighted_bipartisan2, na.rm = TRUE),
            .by = session_year) |> 
  ggplot(aes(x = session_year)) + 
  geom_line(aes(y = total_bipartisan1, color = "Bipartisan1"), group = 1) +
  geom_line(aes(y = total_bipartisan2, color = "Bipartisan2"), group = 1) +
  geom_line(aes(y = weighted_total_bipartisan2, color = "Weighted Bipartisan2"), group = 1, alpha = 0.8) +
  labs(title = "Bipartisanship by Session Year", 
       x = "Session Year", 
       y = "Count of Bipartisan Bills") +
  scale_color_brewer(palette = "Set1") + 
  theme_ipsum()

#How has bipartisanship (1, 2) changed over time?
#Graphing (percentages)
#Note: Spikes in 2009-2010 and 2015-2016 sessions
#Note: bipartisan2 is a subset of bipartisan1, so it should be less than or equal to bipartisan1
bipartisan_count <- bills_SB_AB_bipartisanship |>
  summarize(average_bipartisan1 = mean(bipartisan1, na.rm = TRUE), 
            average_bipartisan2 = mean(bipartisan2, na.rm = TRUE), 
            weighted_average_bipartisan2 = mean(weighted_bipartisan2, na.rm = TRUE),
            .by = session_year) |> 
  ggplot(aes(x = session_year)) + 
  geom_line(aes(y = average_bipartisan1, color = "Bipartisan1 Proportion"), group = 1) +
  geom_line(aes(y = average_bipartisan2, color = "Bipartisan2 Proportion"), group = 1) +
  geom_line(aes(y = weighted_average_bipartisan2, color = "Weighted Bipartisan2 Proportion"), group = 1, alpha = 0.8) +
  labs(title = "Bipartisanship by Session Year", 
       x = "Session Year", 
       y = "Proportion of Bipartisan Bills") +
  scale_color_brewer(palette = "Set1") + 
  theme_ipsum()

#What percentage of bills are bipartisan?
#Note: Around 12.3% for bipartisan1 and 9% for bipartisan2
bipartisan_statistics <- bills_SB_AB_bipartisanship |>
  summarize(total_bipartisan1 = mean(bipartisan1, na.rm = TRUE), 
            total_bipartisan2 = mean(bipartisan2, na.rm = TRUE))

#Graphing (bipartisan3)
#Note: when bipartisanship occurs, it usually occurs in 2:1 (presumably democratic majority) ratios
#Note: fairly consistent trends across years
bipartisan3_score <- bills_SB_AB_bipartisanship |>
  #Only look at when bipartisanship actually occurs
  filter(bipartisan3 > 0) |>
  summarize(average_bipartisan3 = mean(bipartisan3, na.rm = TRUE), 
            median_bipartisan3 = median(bipartisan3, na.rm = TRUE), 
            weighted_average_bipartisan3 = mean(weighted_bipartisan3, na.rm = TRUE),
            .by = session_year) |> 
  ggplot(aes(x = session_year)) + 
  geom_line(aes(y = average_bipartisan3, color = "Average Bipartisan3", group = 1)) + 
  geom_line(aes(y = median_bipartisan3, color = "Median Bipartisan3", group = 1)) +
  geom_line(aes(y = weighted_average_bipartisan3, color = "Weighted Average Bipartisan3", group = 1), alpha = 0.8) +
  labs(title = "Bipartisanship3 Score by Session Year", 
       x = "Session Year", 
       y = "Bipartisanship3 Score") + 
  scale_y_continuous(limits = c(0, 1)) +
  theme_ipsum()

#Histogram
#Note: Obviously vast majority have score of 0 so we remove them 
#Note: Peaks at 1 and 0.50 imply equal party or 2:1 ratios are the most popular
bipartisan3_histogram <- bills_SB_AB_bipartisanship |>
  filter(bipartisan3 > 0) |>
  ggplot(aes(x = bipartisan3)) + 
  geom_histogram(bins = 30, fill = "#F8766D", color = "black") +
  labs(title = "Bipartisanship3 Score Histogram", 
       x = "Bipartisanship3 Score", 
       y = "Count") + 
  theme_ipsum()

#Weighted
#Note: More evenly distributed, still peaks at close to 0.6
#Note: Lower number of values close to 1 implies that bipartisanship does not usually occur 
#in proportion to the party percentages in the legislature 
bipartisan3_histogram_weighted <- bills_SB_AB_bipartisanship |>
  filter(bipartisan3 > 0) |>
  ggplot(aes(x = weighted_bipartisan3)) + 
  geom_histogram(bins = 30, fill = "#F8766D", color = "black") +
  labs(title = "Weighted Bipartisanship3 Score Histogram", 
       x = "Weighted Bipartisanship3 Score", 
       y = "Count") + 
  theme_ipsum()

#How many fully partisan bills are Republic or Democrat? 
#Note: Democrats have consistently sponsored more fully partisan bills than Republicans (unsurprising)
#Note: Decline in Republican proportion of fully partisan bills over time 
fully_partisan <- bills_SB_AB_bipartisanship |> filter(minority_sponsors == 0) |>
  mutate(party_partisanship = ifelse(republican_sponsors > democrat_sponsors, "R", "D")) |>
  summarize(count = n(), 
            .by = c(party_partisanship, session_year)) |>
  ggplot(aes(x = session_year, y = count, fill = party_partisanship)) +
  geom_bar(stat = "identity", position = "fill") +
  scale_y_continuous(labels = scales::percent_format()) +
  labs(title = "Proportion of Fully Partisan Bills by Party and Session Year", 
       x = "Session Year", 
       y = "Proportion of Fully Partisan Bills",
       fill = "Party") + 
  theme_ipsum() + 
  scale_fill_manual(values = c("D" = "#00BFC4", "R" = "#F8766D"))

#Weighted
#Note: For the most part, when weighted, both sides sponsor fully partisan bills equally 
fully_partisan_weighted <- bills_SB_AB_bipartisanship |> filter(minority_sponsors == 0) |>
  mutate(party_partisanship = ifelse(republican_sponsors > democrat_sponsors, "R", "D")) |>
  summarize(count = n(),
            republican_percentage = first(republican_percentage), 
            democrat_percentage = first(democrat_percentage),
            .by = c(party_partisanship, session_year)) |>
  mutate(weighted_count = ifelse(party_partisanship == "R", 
                             count/republican_percentage, 
                             count/democrat_percentage)) |>
  ggplot(aes(x = session_year, y = weighted_count, fill = party_partisanship)) +
  geom_bar(stat = "identity", position = "fill") +
  scale_y_continuous(labels = scales::percent_format()) +
  labs(title = "Proportion of Fully (Weighted) Partisan Bills by Party and Session Year", 
       x = "Session Year", 
       y = "Proportion of Fully (Weighted) Partisan Bills",
       fill = "Party") + 
  theme_ipsum() + 
  scale_fill_manual(values = c("D" = "#00BFC4", "R" = "#F8766D"))

#Do Republicans sponsor more bills than Democrats?
#Note: Democrats sponsor more bills than Republicans (unsurprising, given Democratic majority in California)
#Note: The gap between Republican and Democratic sponsorship has widened in recent years
bipartisanship_totals <- bills_SB_AB_bipartisanship |>
  summarize(total_republican_sponsors = sum(republican_sponsors, na.rm = TRUE), 
            total_democrat_sponsors = sum(democrat_sponsors, na.rm = TRUE),
            difference = total_republican_sponsors - total_democrat_sponsors,
            .by = session_year) |>
  ggplot(aes(x = session_year)) + 
  geom_line(aes(y = difference, group = 1, color = "difference")) + 
  labs(title = "Difference in Republican and Democrat Sponsors by Session Year", 
       x = "Session Year", 
       y = "Difference in Sponsors") +
  theme_ipsum() + 
  theme(legend.position = "none")  

#Weighted
#Note: This gap has actually dramatically shortened!
#Note: Republican actually sponsoring more than Democrats in recent years (with respect to their party proportion)
bipartisanship_totals_weighted <- bills_SB_AB_bipartisanship |>
  summarize(weighted_total_republican_sponsors = sum(weighted_republican_sponsors, na.rm = TRUE), 
            weighted_total_democrat_sponsors = sum(weighted_democrat_sponsors, na.rm = TRUE),
            weighted_difference = weighted_total_republican_sponsors - weighted_total_democrat_sponsors,
            .by = session_year) |>
  ggplot(aes(x = session_year)) + 
  geom_line(aes(y = weighted_difference, group = 1, color = "weighted difference")) + 
  labs(title = "Weighted Difference in Republican and Democrat Sponsors by Session Year", 
       x = "Session Year", 
       y = "Weighted Difference in Sponsors") +
  theme_ipsum() + 
  theme(legend.position = "none")

#How has party-majority bipartisanship changed over time?
bipartisanship_majority <- bills_SB_AB_bipartisanship |> filter(minority_sponsors != 0) |>
  mutate(party_partisanship = ifelse(republican_sponsors > democrat_sponsors, "R", "D")) |>
  summarize(count = n(), 
            .by = c(party_partisanship, session_year)) |>
  ggplot(aes(x = session_year, y = count, fill = party_partisanship)) +
  geom_bar(stat = "identity", position = "fill") +
  scale_y_continuous(labels = scales::percent_format()) +
  labs(title = "Proportion of Party-Majority Bipartisan Bills by Party and Session Year", 
       x = "Session Year", 
       y = "Proportion of Party-Majority Bipartisan Bills",
       fill = "Party") + 
  theme_ipsum() + 
  scale_fill_manual(values = c("D" = "#00BFC4", "R" = "#F8766D"))

#Weighted
#Note: Looks like Republicans are sponsoring more party-majority bills in recent years (almost half)
bipartisanship_majority_weighted <- bills_SB_AB_bipartisanship |> filter(minority_sponsors != 0) |>
  mutate(party_partisanship = ifelse(republican_sponsors > democrat_sponsors, "R", "D")) |>
  summarize(count = n(),
            republican_percentage = first(republican_percentage), 
            democrat_percentage = first(democrat_percentage),
            .by = c(party_partisanship, session_year)) |>
  mutate(weighted_count = ifelse(party_partisanship == "R", 
                                 count/republican_percentage, 
                                 count/democrat_percentage)) |>
  ggplot(aes(x = session_year, y = weighted_count, fill = party_partisanship)) +
  geom_bar(stat = "identity", position = "fill") +
  scale_y_continuous(labels = scales::percent_format()) +
  labs(title = "Proportion of Party-Majority (Weighted) Bipartisan Bills by Party and Session Year", 
       x = "Session Year", 
       y = "Proportion of Party-Majority (Weighted) Bipartisan Bills",
       fill = "Party") + 
  theme_ipsum() + 
  scale_fill_manual(values = c("D" = "#00BFC4", "R" = "#F8766D"))

